In [228]:
import json
import pandas as pd
data_path = '../data/Phase_1/train.json'
with open(data_path) as f:
    data = json.load(f)

len(data)

2000

In [229]:
data_path_test = '../data/Phase_1/test.json'
with open(data_path_test) as f:
    data_test = json.load(f)

len(data_test)

28

In [230]:
import io

def parse_csv_block(text):
    if text is None or text.strip() == "":
        return None
    return pd.read_csv(io.StringIO(text), sep="|")

In [231]:
rows = []

for s in data:
    row = {}
    
    # ---------- label ----------
    row["tag"] = s.get("tag")
    row["num_options"] = len(s["task"]["options"])
    row["answer"] = s.get("answer")
    
    # ---------- context ----------
    ctx = s["context"]
    row["context_description"] = ctx["description"]
    
    net = ctx["wireless_network_information"]
    row["network_type"] = net["network_type"]
    row["num_base_stations"] = int(net["num_base_stations"])
    row["mobility_scenario"] = net["mobility_scenario"]
    
    # ---------- data ----------
    d = s["data"]
    
    def get_shape(df):
        if df is None:
            return 0, 0
        return df.shape[1], df.shape[0]  # cols, rows
    
    # user plane
    df = parse_csv_block(d.get("user_plane_data"))
    row["user_plane_cols"], row["user_plane_rows"] = get_shape(df)
    
    # network config
    df = parse_csv_block(d.get("network_configuration_data"))
    row["config_cols"], row["config_rows"] = get_shape(df)
    
    # signaling
    df = parse_csv_block(d.get("signaling_plane_data"))
    row["signaling_cols"], row["signaling_rows"] = get_shape(df)
    
    # traffic
    df = parse_csv_block(d.get("traffic_data"))
    row["traffic_cols"], row["traffic_rows"] = get_shape(df)
    
    # MR
    df = parse_csv_block(d.get("mr_data"))
    row["mr_cols"], row["mr_rows"] = get_shape(df)
    
    # ---------- metadata ----------
    row["notes"] = d.get("notes")
    row["collection_method"] = d.get("collection_method")
    
    # ---------- tools ----------
    t = s["tools"]
    row["tools_description"] = t.get("description")
    row["tools_capabilities"] = ",".join(t.get("capabilities", []))
    
    rows.append(row)

df_meta = pd.DataFrame(rows)
df_meta.head()

,tag,num_options,answer,context_description,network_type,num_base_stations,mobility_scenario,user_plane_cols,user_plane_rows,config_cols,...,signaling_cols,signaling_rows,traffic_cols,traffic_rows,mr_cols,mr_rows,notes,collection_method,tools_description,tools_capabilities
0,multiple-answer,22,C2|C8|C11|C16,A network engineer conducted drive testing wit...,5G,5,vehicle-based drive test,32,12,28,...,3,22,14,5,14,5,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval
1,single-answer,22,C9,A network engineer conducted drive testing wit...,5G,4,vehicle-based drive test,32,12,28,...,3,10,14,4,14,8,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval
2,single-answer,22,C16,A network engineer conducted drive testing wit...,5G,4,vehicle-based drive test,32,12,28,...,3,10,14,4,14,7,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval
3,single-answer,22,C10,A network engineer conducted drive testing wit...,5G,4,vehicle-based drive test,32,12,28,...,3,10,14,4,14,6,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval
4,single-answer,22,C3,A network engineer conducted drive testing wit...,5G,4,vehicle-based drive test,32,12,28,...,3,10,14,4,14,6,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval

In [232]:
df_meta.describe()

,num_options,num_base_stations,user_plane_cols,user_plane_rows,config_cols,config_rows,signaling_cols,signaling_rows,traffic_cols,traffic_rows,mr_cols,mr_rows
count,2000.0,2000.000000,2000.0,2000.0,2000.0,2000.000000,2000.0,2000.000000,2000.0,2000.000000,2000.0,2000.000000
mean,22.0,5.138000,32.0,12.0,28.0,5.138000,3.0,10.369000,14.0,5.138000,14.0,6.439000
std,0.0,2.944026,0.0,0.0,0.0,2.944026,0.0,2.938393,0.0,2.944026,0.0,1.129565
min,22.0,4.000000,32.0,12.0,28.0,4.000000,3.0,4.000000,14.0,4.000000,14.0,5.000000
25%,22.0,4.000000,32.0,12.0,28.0,4.000000,3.0,10.000000,14.0,4.000000,14.0,5.000000
50%,22.0,4.000000,32.0,12.0,28.0,4.000000,3.0,10.000000,14.0,4.000000,14.0,6.000000
75%,22.0,4.000000,32.0,12.0,28.0,4.000000,3.0,12.000000,14.0,4.000000,14.0,7.000000
max,22.0,13.000000,32.0,12.0,28.0,13.000000,3.0,22.000000,14.0,13.000000,14.0,8.000000

In [233]:
df_meta["num_answers"] = df_meta["answer"].apply(lambda x: len(x.split("|")) if x else 0)

df_meta["num_answers"].value_counts()

num_answers
1    1701
2     228
4      71
Name: count, dtype: int64

In [234]:
df_meta["tag"].value_counts()

tag
single-answer      1701
multiple-answer     299
Name: count, dtype: int64

In [235]:
df_meta["num_base_stations"].value_counts()

num_base_stations
4     1684
13     245
5       71
Name: count, dtype: int64

In [236]:
df_meta[[
    "user_plane_rows",
    "signaling_rows",
    "traffic_rows",
    "mr_rows"
]].describe()

       user_plane_rows  signaling_rows  traffic_rows      mr_rows
count           2000.0     2000.000000   2000.000000  2000.000000
mean              12.0       10.369000      5.138000     6.439000
std                0.0        2.938393      2.944026     1.129565
min               12.0        4.000000      4.000000     5.000000
25%               12.0       10.000000      4.000000     5.000000
50%               12.0       10.000000      4.000000     6.000000
75%               12.0       12.000000      4.000000     7.000000
max               12.0       22.000000     13.000000     8.000000

In [237]:
df_meta[[
    "user_plane_cols",
    "signaling_cols",
    "traffic_cols",
    "mr_rows"
]].describe()

       user_plane_cols  signaling_cols  traffic_cols      mr_rows
count           2000.0          2000.0        2000.0  2000.000000
mean              32.0             3.0          14.0     6.439000
std                0.0             0.0           0.0     1.129565
min               32.0             3.0          14.0     5.000000
25%               32.0             3.0          14.0     5.000000
50%               32.0             3.0          14.0     6.000000
75%               32.0             3.0          14.0     7.000000
max               32.0             3.0          14.0     8.000000

In [238]:
df_meta.isnull().mean()

tag                    0.0
num_options            0.0
answer                 0.0
context_description    0.0
network_type           0.0
num_base_stations      0.0
mobility_scenario      0.0
user_plane_cols        0.0
user_plane_rows        0.0
config_cols            0.0
config_rows            0.0
signaling_cols         0.0
signaling_rows         0.0
traffic_cols           0.0
traffic_rows           0.0
mr_cols                0.0
mr_rows                0.0
notes                  0.0
collection_method      0.0
tools_description      0.0
tools_capabilities     0.0
num_answers            0.0
dtype: float64

In [239]:
df_meta['collection_method'].unique()

<ArrowStringArray>
['Drive testing performed by an engineer']
Length: 1, dtype: str

In [240]:
from collections import defaultdict

all_options = []

for s in data:
    for opt in s["task"]["options"]:
        all_options.append({
            "scenario_id": s["scenario_id"],
            "option_id": opt["id"],
            "label": opt["label"]
        })

import pandas as pd
df_options = pd.DataFrame(all_options)

df_options.head()

,scenario_id,option_id,label
0,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C1,Add neighbor relationship between 3267220_2 an...
1,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C2,Decrease transmission power for 3279943_1
2,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C3,Increase transmission power for 3267220_2
3,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C4,Check test server and transmission issues
4,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C5,Decrease CovInterFreqA2RsrpThld and CovInterFr...

In [241]:
df_options

,scenario_id,option_id,label
0,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C1,Add neighbor relationship between 3267220_2 an...
1,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C2,Decrease transmission power for 3279943_1
2,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C3,Increase transmission power for 3267220_2
3,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C4,Check test server and transmission issues
4,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C5,Decrease CovInterFreqA2RsrpThld and CovInterFr...
...,...,...,...
43995,6a686272-80c5-4a77-ba51-192998460176,C18,Increase A3 Offset threshold for 3230521_4
43996,6a686272-80c5-4a77-ba51-192998460176,C19,Check test server and transmission issues
43997,6a686272-80c5-4a77-ba51-192998460176,C20,Insufficient data; more data is needed for jud...
43998,6a686272-80c5-4a77-ba51-192998460176,C21,Decrease CovInterFreqA2RsrpThld and CovInterFr...
43999,6a686272-80c5-4a77-ba51-192998460176,C22,Modify PdcchOccupiedSymbolNum to 2SYM for 3230...

In [242]:
import re

def normalize_label(label):
    label = label.lower()
    
    # remove cell IDs like 3279943_1
    label = re.sub(r'\d+_\d+', 'CELL', label)
    
    # remove standalone numbers (angles, thresholds)
    label = re.sub(r'\d+', 'NUM', label)
    
    # clean spaces
    label = re.sub(r'\s+', ' ', label).strip()
    
    return label

df_options["normalized"] = df_options["label"].apply(normalize_label)

In [243]:
df_options

,scenario_id,option_id,label,normalized
0,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C1,Add neighbor relationship between 3267220_2 an...,add neighbor relationship between CELL and CELL
1,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C2,Decrease transmission power for 3279943_1,decrease transmission power for CELL
2,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C3,Increase transmission power for 3267220_2,increase transmission power for CELL
3,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C4,Check test server and transmission issues,check test server and transmission issues
4,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C5,Decrease CovInterFreqA2RsrpThld and CovInterFr...,decrease covinterfreqaNUMrsrpthld and covinter...
...,...,...,...,...
43995,6a686272-80c5-4a77-ba51-192998460176,C18,Increase A3 Offset threshold for 3230521_4,increase aNUM offset threshold for CELL
43996,6a686272-80c5-4a77-ba51-192998460176,C19,Check test server and transmission issues,check test server and transmission issues
43997,6a686272-80c5-4a77-ba51-192998460176,C20,Insufficient data; more data is needed for jud...,insufficient data; more data is needed for jud...
43998,6a686272-80c5-4a77-ba51-192998460176,C21,Decrease CovInterFreqA2RsrpThld and CovInterFr...,decrease covinterfreqaNUMrsrpthld and covinter...
43999,6a686272-80c5-4a77-ba51-192998460176,C22,Modify PdcchOccupiedSymbolNum to 2SYM for 3230...,modify pdcchoccupiedsymbolnum to NUMsym for CELL

In [244]:
df_options["normalized"].value_counts()

normalized
add neighbor relationship between CELL and CELL                                          4000
decrease transmission power for CELL                                                     4000
increase transmission power for CELL                                                     4000
decrease covinterfreqaNUMrsrpthld and covinterfreqaNUMrsrpthldNUM thresholds for CELL    4000
press down the tilt angle of CELL by NUM degrees                                         4000
modify pdcchoccupiedsymbolnum to NUMsym for CELL                                         4000
adjust the azimuth of CELL by NUM degrees                                                4000
increase aNUM offset threshold for CELL                                                  4000
lift the tilt angle of CELL by NUM degrees                                               4000
decrease aNUM offset threshold for CELL                                                  4000
check test server and transmission issues                                                2000
insufficient data; more data is needed for judgment.                                     2000
Name: count, dtype: int64

In [245]:
LABEL_SPACE = [
    "add_neighbor",
    "decrease_power",
    "increase_power",
    "decrease_threshold",
    "tilt_down",
    "modify_pdcch",
    "adjust_azimuth",
    "increase_a3",
    "tilt_up",
    "decrease_a3",
    "check_transport",
    "insufficient_data"
]

In [246]:
def map_to_category(norm_label):
    if "neighbor" in norm_label:
        return "add_neighbor"
    if "decrease transmission power" in norm_label:
        return "decrease_power"
    if "increase transmission power" in norm_label:
        return "increase_power"
    if "covinterfreq" in norm_label:
        return "decrease_threshold"
    if "press down the tilt" in norm_label:
        return "tilt_down"
    if "lift the tilt" in norm_label:
        return "tilt_up"
    if "pdcch" in norm_label:
        return "modify_pdcch"
    if "azimuth" in norm_label:
        return "adjust_azimuth"
    if "increase a" in norm_label:
        return "increase_a3"
    if "decrease a" in norm_label:
        return "decrease_a3"
    if "test server" in norm_label:
        return "check_transport"
    if "insufficient" in norm_label:
        return "insufficient_data"
    return "unknown"

In [247]:
import numpy as np

def build_multilabel(scenario):
    id_to_label = {opt["id"]: opt["label"] for opt in scenario["task"]["options"]}
    
    vec = np.zeros(len(LABEL_SPACE))
    
    for cid in scenario["answer"].split("|"):
        label = id_to_label[cid]
        norm = normalize_label(label)
        cat = map_to_category(norm)
        
        if cat in LABEL_SPACE:
            idx = LABEL_SPACE.index(cat)
            vec[idx] = 1
    
    return vec

In [248]:
multi_labels = np.array([build_multilabel(s) for s in data])

multi_labels.shape

(2000, 12)

In [249]:
label_counts = multi_labels.sum(axis=0)

for label, count in zip(LABEL_SPACE, label_counts):
    print(label, count)

add_neighbor 240.0
decrease_power 157.0
increase_power 142.0
decrease_threshold 245.0
tilt_down 157.0
modify_pdcch 240.0
adjust_azimuth 142.0
increase_a3 71.0
tilt_up 254.0
decrease_a3 231.0
check_transport 239.0
insufficient_data 252.0

In [250]:
co_matrix = multi_labels.T @ multi_labels

import pandas as pd
pd.DataFrame(co_matrix, index=LABEL_SPACE, columns=LABEL_SPACE)

,add_neighbor,decrease_power,increase_power,decrease_threshold,tilt_down,modify_pdcch,adjust_azimuth,increase_a3,tilt_up,decrease_a3,check_transport,insufficient_data
add_neighbor,240.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
decrease_power,0.0,157.0,0.0,0.0,157.0,0.0,0.0,71.0,0.0,0.0,0.0,0.0
increase_power,0.0,0.0,142.0,0.0,0.0,0.0,142.0,0.0,0.0,0.0,0.0,0.0
decrease_threshold,0.0,0.0,0.0,245.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tilt_down,0.0,157.0,0.0,0.0,157.0,0.0,0.0,71.0,0.0,0.0,0.0,0.0
modify_pdcch,0.0,0.0,0.0,0.0,0.0,240.0,0.0,0.0,0.0,0.0,0.0,0.0
adjust_azimuth,0.0,0.0,142.0,0.0,0.0,0.0,142.0,0.0,0.0,0.0,0.0,0.0
increase_a3,0.0,71.0,0.0,0.0,71.0,0.0,0.0,71.0,0.0,0.0,0.0,0.0
tilt_up,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,254.0,0.0,0.0,0.0
decrease_a3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,231.0,0.0,0.0
check_transport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,239.0,0.0
insufficient_data,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,252.0

In [251]:
df_options[df_options['normalized']=='increase aNUM offset threshold for CELL']

,scenario_id,option_id,label,normalized
10,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C11,Increase A3 Offset threshold for 3279943_1,increase aNUM offset threshold for CELL
15,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,C16,Increase A3 Offset threshold for 3267220_2,increase aNUM offset threshold for CELL
29,0cd874c0-eab3-4963-a51f-28fc5e004ed8,C8,Increase A3 Offset threshold for 3213751_2,increase aNUM offset threshold for CELL
41,0cd874c0-eab3-4963-a51f-28fc5e004ed8,C20,Increase A3 Offset threshold for 3244912_3,increase aNUM offset threshold for CELL
47,ac53a506-f1dd-404f-bb93-1ffb337ce0e6,C4,Increase A3 Offset threshold for 3211229_4,increase aNUM offset threshold for CELL
...,...,...,...,...
43950,7b3003fb-9bf3-41b7-9eeb-306aa46d8726,C17,Increase A3 Offset threshold for 3236210_3,increase aNUM offset threshold for CELL
43969,bbbf0187-a422-40c0-83b9-93e232cfb17f,C14,Increase A3 Offset threshold for 3264819_3,increase aNUM offset threshold for CELL
43974,bbbf0187-a422-40c0-83b9-93e232cfb17f,C19,Increase A3 Offset threshold for 3238922_2,increase aNUM offset threshold for CELL
43992,6a686272-80c5-4a77-ba51-192998460176,C15,Increase A3 Offset threshold for 3266352_3,increase aNUM offset threshold for CELL
43995,6a686272-80c5-4a77-ba51-192998460176,C18,Increase A3 Offset threshold for 3230521_4,increase aNUM offset threshold for CELL

In [252]:
multi_labels

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2000, 12))

In [253]:
np.array(df_options['scenario_id'].unique().tolist())[np.where(multi_labels[:, 7] == 1)[0]]

array(['08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e',
       '6fc2c635-2c2a-4f1c-9ce0-db0d4c53b46a',
       '65e93bbb-6649-4c6f-b760-df22ae943159',
       '60725196-a864-4d24-97d2-3ed06582f9a6',
       '4ad88a7d-acb2-4cc0-bd46-650731073814',
       '3da2462e-a0e1-415f-814a-130b8bb10a6b',
       '8d981055-ccdd-43a3-b89c-24b902fcd24b',
       'd6fae17f-d308-4353-a0a9-9173ea702491',
       'a21308d3-6c7d-43ba-907f-e0eec2a8d108',
       'ec76b540-cc3b-45f1-9336-0571d8ee35cb',
       '76da2a11-8643-40d3-8369-928e46cf3f45',
       '63791e7d-0638-4293-8d77-11fa0d01c2c0',
       '0739c14e-bec3-45e6-bc58-8209cc2ceb7f',
       'e05914bb-e6c9-4db4-8294-4d6b6d7f2167',
       '7e6844f5-d1b8-4690-b54c-89bd236b1aed',
       '39c15917-132f-491c-8bda-fc1b5ad1c816',
       '4493a284-8bfc-4e1a-8c64-d5763f3f48dc',
       '2f62bb6a-b3ab-4a0a-823a-ba1d5f618a31',
       '78d4b233-8f06-4dc3-83ce-236548d291c3',
       '416a5366-8e5e-4de0-ad5e-788028ace4f4',
       '5f6743f9-7466-4949-afcc-4abff69b29aa',
       '9a5f6799-f924-4560-aa57-fbae731b69cf',
       '844a4562-9bd2-4b3a-837e-4a4e09f0ecf9',
       'e9e4b3d2-b7cc-423b-853f-263517b45d07',
       '46de010f-263a-45f5-a5d2-d50e34dcefe7',
       'a3f64df0-b5f0-4c29-bfb3-faf91461a69f',
       '76ca4839-ae57-40ae-b691-fb2b96de77e3',
       'f0325075-a124-4d71-840c-6424b5feb653',
       'd37ff5ce-db1b-4bab-958c-35ac5b4e2105',
       'c9b13772-4c0e-443a-99cd-2debb0836f3a',
       '126877f7-f338-4283-bd26-375829888301',
       '6346519a-6369-4c75-9d61-48988489afdd',
       '10cf1f13-a5b8-4782-aac9-e1a900b5ff5f',
       'df1443d0-ac2c-4a34-8dac-2778025b9865',
       '33f2cc7f-79f9-4385-86c7-c6789ee35a93',
       'b765e7ea-2b43-4356-8a21-0febd334d22b',
       '5bab95fb-d92b-40cb-9d97-00a0fe63fdbe',
       '2cb06c21-e33f-410a-8f1f-813604af8f79',
       '7fa5ac18-5570-49d4-a335-bc0250b3dffc',
       'abdcb0e4-a5cc-4fef-ba4f-d5c52958f247',
       '1b77d60a-60c4-4cfc-82cd-edd9a42dc97b',
       '75f92daf-9997-4299-8bd8-2ea604c6c602',
       '0aed7aa1-073c-4850-9415-2ca739039de3',
       '643e7382-2961-479c-be28-11500e272244',
       '716fdee2-00e6-4391-aa1a-a69d49b01715',
       '64bc2b02-123e-4dbd-8fd2-ba28ee693eda',
       'ea1d036c-15ee-4fb4-a4f7-1a6616344356',
       'cd1d619b-ff4b-4477-9020-1ab8e4b277cc',
       '51fc4268-8281-40cf-ac7d-01738e5b53b1',
       '099cc5ee-2b2a-44f0-b377-d6f701957288',
       'a2ab62a8-b7e1-4f40-a477-021589e1d75d',
       '815c1a8e-b795-453c-b8e8-d8b4e21bf75a',
       '2ab21f3b-0f44-4620-b20f-b184cbf3e18c',
       'd8b67895-51da-4ba1-8c1c-97dd8e61eb3a',
       '8385a992-e6b7-4bf9-a33f-7695bcc3d7b9',
       'ed2e142e-3e97-43bb-9f45-197641c4bcaf',
       '6915143c-6918-4e15-8471-505c0bbe0308',
       'e3447584-b8a9-4b2f-9a06-08453d21996d',
       'f9279b59-6841-4602-82ed-6ed0460835c0',
       '71b90755-e8d8-45fd-8af4-d0f0d8b6d3d0',
       'c0114e44-c0b3-4459-8658-9e187a9d6a2a',
       'dd612ece-57dc-4841-937b-040c8f7729a1',
       'd0ee46a6-dee1-427b-8eef-e4e40fd26839',
       '84e4a106-0914-4853-9e40-3d2ce02c675f',
       '898c6f88-51e5-424b-8b33-2fe06d60aa94',
       '8820a8fd-b3b2-4375-a5a0-5d3c53298442',
       'dc153043-f07f-4f0d-addf-f87a6611be3d',
       '7c19866a-9e68-4910-94b0-d23e876109eb',
       'f36c997d-9c46-426d-80c8-5a40740a51ea',
       '1af10cf0-d489-46b2-b4ae-20c1b74d12aa',
       'e9fe0c0f-3fd8-47b2-a39d-ab3c957055c1'], dtype='<U36')

In [254]:
#check
def build_category_counts(scenario):
    id_to_label = {opt["id"]: opt["label"] for opt in scenario["task"]["options"]}
    
    counts = {k: 0 for k in LABEL_SPACE}
    
    for cid in scenario["answer"].split("|"):
        label = id_to_label[cid]
        norm = normalize_label(label)
        cat = map_to_category(norm)
        
        if cat in counts:
            counts[cat] += 1
    
    return counts
cat_counts = [build_category_counts(s) for s in data]
df_counts = pd.DataFrame(cat_counts)
double_increase_a3 = (df_counts["increase_a3"] >= 2).sum()
double_increase_a3

np.int64(71)

In [255]:
len(np.array(df_options['scenario_id'].unique().tolist())[np.where(multi_labels[:, 7] == 1)[0]])

71

In [256]:
np.where(multi_labels[:, 0] == 1)

(array([  20,   32,   42,   47,   52,   54,   58,   66,   74,   88,   95,
         106,  108,  124,  139,  140,  150,  151,  152,  153,  158,  167,
         178,  190,  191,  203,  205,  210,  223,  225,  248,  251,  259,
         270,  271,  272,  292,  296,  304,  305,  306,  315,  323,  335,
         337,  345,  347,  349,  355,  367,  370,  371,  392,  405,  413,
         417,  424,  426,  427,  436,  444,  454,  468,  492,  493,  499,
         503,  523,  531,  539,  556,  566,  567,  590,  601,  608,  611,
         626,  633,  680,  713,  714,  726,  731,  732,  742,  746,  762,
         769,  773,  781,  782,  787,  790,  797,  798,  808,  832,  878,
         884,  885,  886,  887,  893,  895,  906,  908,  918,  925,  926,
         931,  933,  934,  973,  978,  980,  987,  991,  993, 1004, 1010,
        1036, 1047, 1052, 1055, 1062, 1066, 1069, 1071, 1077, 1078, 1080,
        1084, 1096, 1105, 1113, 1117, 1118, 1122, 1130, 1136, 1143, 1146,
        1156, 1163, 1168, 1199, 1202, 1203, 1205, 1218, 1224, 1255, 1261,
        1262, 1271, 1279, 1286, 1291, 1292, 1304, 1311, 1317, 1327, 1329,
        1335, 1338, 1367, 1390, 1393, 1409, 1410, 1411, 1412, 1417, 1419,
        1429, 1439, 1448, 1450, 1451, 1457, 1466, 1469, 1492, 1494, 1498,
        1502, 1508, 1511, 1524, 1530, 1532, 1536, 1539, 1561, 1590, 1602,
        1603, 1630, 1635, 1648, 1649, 1661, 1669, 1670, 1688, 1699, 1701,
        1718, 1720, 1761, 1783, 1793, 1799, 1801, 1802, 1818, 1822, 1824,
        1827, 1831, 1832, 1849, 1851, 1855, 1857, 1880, 1889, 1892, 1893,
        1903, 1912, 1914, 1919, 1938, 1950, 1955, 1990, 1995]),)

In [257]:
df_options.iloc[np.where(multi_labels[:, 0] == 1)[0][0]*22]

scenario_id                 30724e42-2186-44df-9fce-eccec04e0470
option_id                                                     C1
label          Insufficient data; more data is needed for jud...
normalized     insufficient data; more data is needed for jud...
Name: 440, dtype: str

In [258]:
df_options.iloc[np.where(multi_labels[:, 3] == 1)[0][0]*22*5]

scenario_id         da7d2a6a-a3ec-43a5-adc9-885ee6844f56
option_id                                             C1
label          Decrease transmission power for 3265550_2
normalized          decrease transmission power for CELL
Name: 1650, dtype: str

In [259]:
df_meta.iloc[np.where(multi_labels[:, 3] == 1)[0]]

,tag,num_options,answer,context_description,network_type,num_base_stations,mobility_scenario,user_plane_cols,user_plane_rows,config_cols,...,signaling_rows,traffic_cols,traffic_rows,mr_cols,mr_rows,notes,collection_method,tools_description,tools_capabilities,num_answers
15,single-answer,22,C14,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,5,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
18,single-answer,22,C12,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,5,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
29,single-answer,22,C4,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,7,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
35,single-answer,22,C17,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,6,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
39,single-answer,22,C22,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,5,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1952,single-answer,22,C6,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,7,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
1956,single-answer,22,C22,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,6,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
1959,single-answer,22,C15,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,5,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
1972,single-answer,22,C12,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,6,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1
1983,single-answer,22,C21,A network engineer conducted drive testing wit...,5G,13,vehicle-based drive test,32,12,28,...,12,14,13,14,7,,Drive testing performed by an engineer,Analytical tools are provided to retrieve the ...,data retrieval,1

In [260]:
len(multi_labels)

2000

In [261]:
multi_labels.sum(axis=1)

array([3., 1., 1., ..., 1., 1., 1.], shape=(2000,))

In [262]:
multi_labels[0]

array([0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.])

In [263]:
LABEL_SPACE

['add_neighbor',
 'decrease_power',
 'increase_power',
 'decrease_threshold',
 'tilt_down',
 'modify_pdcch',
 'adjust_azimuth',
 'increase_a3',
 'tilt_up',
 'decrease_a3',
 'check_transport',
 'insufficient_data']

In [264]:
len(multi_labels)

2000

In [265]:
pd.Series(multi_labels.sum(axis=1)).value_counts()

1.0    1701
2.0     228
3.0      71
Name: count, dtype: int64

In [266]:
def has_add_neighbor(scenario):
    id_to_label = {opt["id"]: opt["label"] for opt in scenario["task"]["options"]}
    
    for cid in scenario["answer"].split("|"):
        label = id_to_label[cid]
        norm = normalize_label(label)
        
        if map_to_category(norm) == "add_neighbor":
            return True
    return False


add_neighbor_cases = [s for s in data if has_add_neighbor(s)]

len(add_neighbor_cases)

240

In [267]:
def extract_features(s):
    import io
    
    d = s["data"]
    
    # --- user plane ---
    df_up = parse_csv_block(d["user_plane_data"])
    
    # serving vs neighbor gap
    serving_rsrp = df_up["5G KPI PCell RF Serving SS-RSRP [dBm]"]
    neighbor_rsrp = df_up[
        "Measurement PCell Neighbor Cell Top Set(Cell Level) Top 1 Filtered Tx BRSRP [dBm]"
    ]
    
    rsrp_gap = (serving_rsrp - neighbor_rsrp).mean()
    
    # throughput
    throughput = df_up["5G KPI PCell Layer2 MAC DL Throughput [Mbps]"]
    
    # PCI switching
    pci_switches = df_up["5G KPI PCell RF Serving PCI"].nunique()
    
    # --- signaling ---
    df_sig = parse_csv_block(d.get("signaling_plane_data"))
    
    if df_sig is not None:
        ho_count = (df_sig["Event Name"] == "NRHandoverAttempt").sum()
        a3_count = (df_sig["Event Name"] == "NREventA3").sum()
    else:
        ho_count = 0
        a3_count = 0
    
    return {
        "rsrp_gap": rsrp_gap,
        "throughput_min": throughput.min(),
        "throughput_mean": throughput.mean(),
        "pci_switches": pci_switches,
        "ho_count": ho_count,
        "a3_count": a3_count
    }

In [268]:
non_add_neighbor_cases = [s for s in data if not has_add_neighbor(s)]

In [269]:
len(non_add_neighbor_cases)

1760

In [270]:
add_feats = pd.DataFrame([extract_features(s) for s in add_neighbor_cases])
non_add_feats = pd.DataFrame([extract_features(s) for s in non_add_neighbor_cases])

In [271]:
add_feats

,rsrp_gap,throughput_min,throughput_mean,pci_switches,ho_count,a3_count
0,-0.037500,26.79,315.913333,1,0,3
1,0.378333,43.73,257.180000,1,0,3
2,0.081667,32.66,315.456667,1,0,3
3,0.158333,28.20,292.205000,1,0,3
4,-0.417500,25.01,314.658333,1,0,3
...,...,...,...,...,...,...
235,-0.503333,31.37,321.041667,1,0,3
236,0.437500,42.45,306.046667,1,0,3
237,0.537500,51.90,322.194167,1,0,3
238,0.245833,35.68,317.848333,1,0,3
239,-0.820833,31.31,329.720833,1,0,3

In [272]:
non_add_feats

,rsrp_gap,throughput_min,throughput_mean,pci_switches,ho_count,a3_count
0,1.964167,25.61,259.289167,2,3,3
1,4.082500,51.10,265.461667,1,1,1
2,0.585000,25.17,250.120000,2,1,1
3,4.010000,60.28,227.875833,1,1,1
4,5.319167,68.04,280.520833,1,1,1
...,...,...,...,...,...,...
1755,3.864167,48.96,261.834167,1,1,1
1756,4.092500,60.52,248.107500,1,1,1
1757,3.655833,47.15,258.708333,1,1,1
1758,2.875833,56.83,283.061667,1,1,1
1759,4.530833,57.70,269.607500,1,1,1

In [273]:
for col in add_feats.columns:
    print(f"\n=== {col} ===")
    print("ADD:", add_feats[col].mean())
    print("NON:", non_add_feats[col].mean())

=== rsrp_gap ===
ADD: 0.003243055555555557
NON: 3.285635416666666

=== throughput_min ===
ADD: 36.73241666666666
NON: 49.10842045454546

=== throughput_mean ===
ADD: 317.73371527777783
NON: 247.51748958333337

=== pci_switches ===
ADD: 1.0
NON: 2.006818181818182

=== ho_count ===
ADD: 0.0
NON: 0.9511363636363637

=== a3_count ===
ADD: 3.0
NON: 0.8119318181818181

In [274]:
import io
import numpy as np
import pandas as pd

def extract_features(s):
    d = s["data"]
    feats = {}
    
    # ---------- USER PLANE ----------
    df_up = parse_csv_block(d.get("user_plane_data"))
    
    if df_up is not None and not df_up.empty:
        th = df_up["5G KPI PCell Layer2 MAC DL Throughput [Mbps]"]
        sinr = df_up["5G KPI PCell RF Serving SS-SINR [dB]"]
        rsrp = df_up["5G KPI PCell RF Serving SS-RSRP [dBm]"]
        
        # --- Throughput (enhanced) ---
        feats["throughput_mean"] = th.mean()
        feats["throughput_min"] = th.min()
        feats["throughput_std"] = th.std()
        feats["throughput_p10"] = np.percentile(th, 10)
        feats["throughput_low_ratio"] = (th < 150).mean()
        feats["throughput_drop_ratio"] = th.min() / (th.max() + 1e-6)
        
        # --- RF ---
        feats["sinr_mean"] = sinr.mean()
        feats["sinr_min"] = sinr.min()
        feats["rsrp_mean"] = rsrp.mean()
        
        # --- RF vs Throughput mismatch ---
        feats["rf_good_flag"] = int((feats["rsrp_mean"] > -95) and (feats["sinr_mean"] > 8))
        feats["low_tp_flag"] = int(feats["throughput_mean"] < 150)
        feats["rf_tp_mismatch"] = int(feats["rf_good_flag"] and feats["low_tp_flag"])
        
        # --- PCI switching ---
        feats["pci_switches"] = df_up["5G KPI PCell RF Serving PCI"].nunique()
        
        # --- Neighbor gap ---
        if "Measurement PCell Neighbor Cell Top Set(Cell Level) Top 1 Filtered Tx BRSRP [dBm]" in df_up.columns:
            neigh = df_up["Measurement PCell Neighbor Cell Top Set(Cell Level) Top 1 Filtered Tx BRSRP [dBm]"]
            feats["rsrp_gap"] = (rsrp - neigh).mean()
            feats["serving_better_ratio"] = (rsrp > neigh).mean()
        else:
            feats["rsrp_gap"] = np.nan
            feats["serving_better_ratio"] = np.nan
        
        # --- 🔥 CCE / PDCCH features (CRITICAL) ---
        if "CCE Fail Rate" in df_up.columns:
            cce = df_up["CCE Fail Rate"]
            feats["cce_fail_mean"] = cce.mean()
            feats["cce_fail_max"] = cce.max()
            feats["cce_fail_high_ratio"] = (cce > 0.4).mean()
        else:
            feats["cce_fail_mean"] = np.nan
            feats["cce_fail_max"] = np.nan
            feats["cce_fail_high_ratio"] = np.nan
        
        # --- Scheduling features ---
        if "Grant" in df_up.columns:
            feats["grant_mean"] = df_up["Grant"].mean()
        else:
            feats["grant_mean"] = np.nan
        
        if "5G KPI PCell Layer1 DL RB Num (Including 0)" in df_up.columns:
            feats["rb_mean"] = df_up["5G KPI PCell Layer1 DL RB Num (Including 0)"].mean()
        else:
            feats["rb_mean"] = np.nan
        
        if "Avg MCS" in df_up.columns:
            feats["mcs_mean"] = df_up["Avg MCS"].mean()
        else:
            feats["mcs_mean"] = np.nan
        
    else:
        feats.update({
            "throughput_mean": np.nan,
            "throughput_min": np.nan,
            "throughput_std": np.nan,
            "throughput_p10": np.nan,
            "throughput_low_ratio": np.nan,
            "throughput_drop_ratio": np.nan,
            "sinr_mean": np.nan,
            "sinr_min": np.nan,
            "rsrp_mean": np.nan,
            "rf_good_flag": 0,
            "low_tp_flag": 0,
            "rf_tp_mismatch": 0,
            "pci_switches": 0,
            "rsrp_gap": np.nan,
            "serving_better_ratio": np.nan,
            "cce_fail_mean": np.nan,
            "cce_fail_max": np.nan,
            "cce_fail_high_ratio": np.nan,
            "grant_mean": np.nan,
            "rb_mean": np.nan,
            "mcs_mean": np.nan
        })
    
    # ---------- SIGNALING ----------
    df_sig = parse_csv_block(d.get("signaling_plane_data"))
    
    if df_sig is not None:
        feats["ho_count"] = (df_sig["Event Name"] == "NRHandoverAttempt").sum()
        feats["a3_count"] = (df_sig["Event Name"] == "NREventA3").sum()
        feats["rrc_reest"] = (df_sig["Event Name"] == "NRRRCReestablishAttempt").sum()
    else:
        feats["ho_count"] = 0
        feats["a3_count"] = 0
        feats["rrc_reest"] = 0
    
    # ---------- CONFIG ----------
    df_cfg = parse_csv_block(d.get("network_configuration_data"))
    
    if df_cfg is not None:
        feats["num_cells"] = len(df_cfg)
        feats["avg_power"] = df_cfg["Transmission Power"].mean()
        feats["avg_tilt"] = df_cfg["Mechanical Downtilt"].mean()
        
        # 🔥 Key config feature
        if "PdcchOccupiedSymbolNum" in df_cfg.columns:
            feats["pdcch_symbols"] = pd.to_numeric(df_cfg["PdcchOccupiedSymbolNum"].str.replace("SYM", ""), errors='coerce').mean()
        else:
            feats["pdcch_symbols"] = np.nan
    else:
        feats["num_cells"] = 0
        feats["avg_power"] = np.nan
        feats["avg_tilt"] = np.nan
        feats["pdcch_symbols"] = np.nan
    
    # ---------- TRAFFIC ----------
    df_tr = parse_csv_block(d.get("traffic_data"))
    
    if df_tr is not None:
        feats["dl_prb_util"] = df_tr["Downlink PRB utilization(%)"].mean()
        feats["ul_prb_util"] = df_tr["Uplink PRB utilization(%)"].mean()
        
        # 🔥 CCE stats (VERY IMPORTANT)
        if "Downlink CCE Allocation Success Rate(%)" in df_tr.columns:
            feats["dl_cce_success"] = df_tr["Downlink CCE Allocation Success Rate(%)"].mean()
        else:
            feats["dl_cce_success"] = np.nan
        
        if "Downlink CCE utilization(%)" in df_tr.columns:
            feats["dl_cce_util"] = df_tr["Downlink CCE utilization(%)"].mean()
        else:
            feats["dl_cce_util"] = np.nan
    else:
        feats["dl_prb_util"] = np.nan
        feats["ul_prb_util"] = np.nan
        feats["dl_cce_success"] = np.nan
        feats["dl_cce_util"] = np.nan
    
    # ---------- MR ----------
    df_mr = parse_csv_block(d.get("mr_data"))
    
    if df_mr is not None:
        feats["mr_throughput_mean"] = df_mr["Throughput(Mbps)"].mean()
        feats["mr_rsrp_mean"] = df_mr["Serving RSRP(dBm)"].mean()
    else:
        feats["mr_throughput_mean"] = np.nan
        feats["mr_rsrp_mean"] = np.nan
    
    # ---------- NEIGHBOR MISSING ----------
    try:
        observed = set()
        for col in df_up.columns:
            if "Neighbor Cell" in col and "PCI" in col:
                observed.update(df_up[col].dropna().astype(str))
        
        config_neighbors = set()
        for x in df_cfg["PCell Neighbor Cell (gNodeBID_ARFCN_PCI)"]:
            if isinstance(x, str):
                parts = x.strip("[]").split(",")
                for p in parts:
                    config_neighbors.add(p.split("_")[-1])
        
        feats["missing_neighbors"] = len(observed - config_neighbors)
    except:
        feats["missing_neighbors"] = 0
    
    # ---------- 🔥 FINAL COMPOSITE FEATURE ----------
    # Strong indicator of PDCCH problem
    try:
        feats["pdcch_problem_score"] = (
            (feats["cce_fail_mean"] if not np.isnan(feats["cce_fail_mean"]) else 0) * 0.5 +
            (1 - feats["dl_cce_success"]/100 if not np.isnan(feats["dl_cce_success"]) else 0) * 0.3 +
            feats["rf_tp_mismatch"] * 0.2
        )
    except:
        feats["pdcch_problem_score"] = np.nan
    
    return feats

In [275]:
X = pd.DataFrame([extract_features(s) for s in data])
X = X.fillna(0)

In [276]:
Y = np.array([build_multilabel(s) for s in data])

In [277]:
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

model = MultiOutputClassifier(RandomForestClassifier(n_estimators=200, random_state=42))
model.fit(X_train, y_train)

/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

MultiOutputClassifier(estimator=RandomForestClassifier(n_estimators=200,
                                                       random_state=42))

In [278]:
X_train

,throughput_mean,throughput_min,throughput_std,throughput_p10,throughput_low_ratio,throughput_drop_ratio,sinr_mean,sinr_min,rsrp_mean,rf_good_flag,...,avg_tilt,pdcch_symbols,dl_prb_util,ul_prb_util,dl_cce_success,dl_cce_util,mr_throughput_mean,mr_rsrp_mean,missing_neighbors,pdcch_problem_score
968,248.230833,29.19,222.685072,31.121,0.500000,0.050703,8.324167,0.28,-98.190000,0,...,5.500000,1.0,12.351575,14.092975,94.854000,0.121900,68.285714,-103.657143,1,0.049188
240,239.074167,23.85,186.953806,49.907,0.416667,0.044109,8.212500,-3.06,-82.356667,1,...,3.250000,1.0,10.565150,10.435075,95.744250,0.170625,112.187500,-81.637500,1,0.059851
819,254.097500,57.43,206.146244,58.523,0.500000,0.100199,12.442500,7.96,-89.684167,1,...,7.500000,1.0,32.202150,35.443900,95.294500,0.189175,50.800000,-87.971429,1,0.067033
692,173.595000,64.83,178.323293,66.649,0.750000,0.133047,7.060000,2.31,-91.877500,0,...,5.923077,1.0,12.728623,11.036592,94.470615,0.149646,114.060000,-94.900000,1,0.067421
420,257.497500,58.93,203.602603,61.067,0.500000,0.098382,12.725000,8.14,-90.166667,1,...,11.500000,1.0,83.605450,86.779250,95.521500,0.165925,51.700000,-87.771429,1,0.063019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,330.902500,32.87,220.260021,39.111,0.333333,0.055446,8.971667,-3.91,-84.695000,1,...,8.250000,1.0,9.231050,12.271500,92.708000,0.229250,151.387500,-90.850000,1,0.071876
1294,173.207500,55.38,176.335966,63.596,0.750000,0.100433,7.521667,2.69,-91.647500,0,...,7.461538,1.0,12.827815,13.706354,92.856846,0.183462,83.428571,-94.714286,1,0.073929
860,213.261667,57.38,144.992209,68.314,0.500000,0.138395,11.695833,7.87,-89.720833,1,...,7.000000,1.0,28.930925,33.647150,93.800750,0.201850,55.442857,-87.857143,1,0.069014
1459,255.360000,49.08,191.626841,62.369,0.500000,0.088067,12.852500,7.29,-89.950000,1,...,1.750000,1.0,9.922600,13.776725,92.685000,0.160675,96.150000,-91.316667,1,0.071112
1126,246.339167,76.57,182.651710,88.819,0.500000,0.132994,12.405000,7.91,-90.295833,1,...,7.500000,1.0,31.860600,30.580725,93.796000,0.186875,52.957143,-88.971429,1,0.055279

In [279]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

for i, label in enumerate(LABEL_SPACE):
    print(f"\n=== {label} ===")
    print(classification_report(y_test[:, i], y_pred[:, i]))

=== add_neighbor ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       352
         1.0       1.00      1.00      1.00        48

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== decrease_power ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       372
         1.0       1.00      1.00      1.00        28

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== increase_power ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       368
         1.0       1.00      1.00      1.00        32

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== decrease_threshold ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       355
         1.0       1.00      1.00      1.00        45

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== tilt_down ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       372
         1.0       1.00      1.00      1.00        28

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== modify_pdcch ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       357
         1.0       1.00      1.00      1.00        43

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== adjust_azimuth ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       368
         1.0       1.00      1.00      1.00        32

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== increase_a3 ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       388
         1.0       1.00      1.00      1.00        12

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== tilt_up ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       355
         1.0       1.00      1.00      1.00        45

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== decrease_a3 ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       358
         1.0       1.00      1.00      1.00        42

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== check_transport ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       335
         1.0       1.00      1.00      1.00        65

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400


=== insufficient_data ===
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       348
         1.0       1.00      1.00      1.00        52

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

In [280]:
exact_match = (y_pred == y_test).all(axis=1).mean()
print("Exact match:", exact_match)

Exact match: 1.0

In [281]:
def iou_score(y_true, y_pred):
    scores = []
    for t, p in zip(y_true, y_pred):
        intersection = np.sum((t == 1) & (p == 1))
        union = np.sum((t == 1) | (p == 1))
        if union == 0:
            scores.append(1)
        else:
            scores.append(intersection / union)
    return np.mean(scores)

print("Mean IoU:", iou_score(y_test, y_pred))

Mean IoU: 1.0

In [282]:
import pandas as pd

for i, label in enumerate(LABEL_SPACE):
    clf = model.estimators_[i]
    
    importances = pd.Series(
        clf.feature_importances_,
        index=X.columns
    ).sort_values(ascending=False)
    
    print(f"\n=== {label} ===")
    print(importances.head(10))

=== add_neighbor ===
rrc_reest               0.210425
throughput_low_ratio    0.202655
a3_count                0.148464
throughput_mean         0.125704
ho_count                0.059520
rsrp_gap                0.051423
serving_better_ratio    0.047538
sinr_min                0.046625
rsrp_mean               0.018091
pci_switches            0.016742
dtype: float64

=== decrease_power ===
ho_count                0.130897
sinr_min                0.127243
serving_better_ratio    0.117894
rsrp_mean               0.091898
mcs_mean                0.091043
rsrp_gap                0.083504
throughput_low_ratio    0.071159
mr_throughput_mean      0.056480
a3_count                0.051844
sinr_mean               0.036108
dtype: float64

=== increase_power ===
mr_rsrp_mean            0.266267
rsrp_mean               0.261066
serving_better_ratio    0.084260
throughput_min          0.052162
rsrp_gap                0.049727
sinr_min                0.045589
a3_count                0.040038
throughput_p10          0.038247
rf_good_flag            0.035379
ho_count                0.031553
dtype: float64

=== decrease_threshold ===
throughput_mean         0.203738
num_cells               0.157193
pci_switches            0.149073
throughput_low_ratio    0.129942
sinr_mean               0.072287
rsrp_mean               0.050209
grant_mean              0.036469
rf_good_flag            0.035837
rb_mean                 0.035580
a3_count                0.034786
dtype: float64

=== tilt_down ===
ho_count                0.130897
sinr_min                0.127243
serving_better_ratio    0.117894
rsrp_mean               0.091898
mcs_mean                0.091043
rsrp_gap                0.083504
throughput_low_ratio    0.071159
mr_throughput_mean      0.056480
a3_count                0.051844
sinr_mean               0.036108
dtype: float64

=== modify_pdcch ===
dl_cce_success         0.196293
pdcch_problem_score    0.173800
cce_fail_high_ratio    0.166576
cce_fail_mean          0.164488
cce_fail_max           0.135403
dl_cce_util            0.079638
grant_mean             0.040364
sinr_mean              0.012570
sinr_min               0.008346
mcs_mean               0.005878
dtype: float64

=== adjust_azimuth ===
mr_rsrp_mean            0.266267
rsrp_mean               0.261066
serving_better_ratio    0.084260
throughput_min          0.052162
rsrp_gap                0.049727
sinr_min                0.045589
a3_count                0.040038
throughput_p10          0.038247
rf_good_flag            0.035379
ho_count                0.031553
dtype: float64

=== increase_a3 ===
ho_count                0.290215
mcs_mean                0.194665
a3_count                0.078220
num_cells               0.076349
mr_throughput_mean      0.048899
sinr_min                0.044911
rsrp_mean               0.042630
throughput_mean         0.035445
throughput_low_ratio    0.033765
pci_switches            0.025962
dtype: float64

=== tilt_up ===
ul_prb_util           0.316974
dl_prb_util           0.298292
rb_mean               0.127658
grant_mean            0.040749
sinr_min              0.029147
mcs_mean              0.024770
sinr_mean             0.024644
avg_tilt              0.021260
mr_throughput_mean    0.020164
dl_cce_success        0.011184
dtype: float64

=== decrease_a3 ===
serving_better_ratio    0.202275
sinr_min                0.135969
throughput_low_ratio    0.120164
pci_switches            0.087981
a3_count                0.074027
sinr_mean               0.063886
rsrp_gap                0.059915
ho_count                0.051432
mr_throughput_mean      0.038597
rrc_reest               0.029960
dtype: float64

=== check_transport ===
grant_mean             0.450936
rb_mean                0.072267
mr_throughput_mean     0.063189
sinr_min               0.053381
dl_prb_util            0.046486
sinr_mean              0.042212
ul_prb_util            0.037780
cce_fail_mean          0.036038
pdcch_problem_score    0.027494
dl_cce_success         0.025549
dtype: float64

=== insufficient_data ===
ul_prb_util           0.371098
dl_prb_util           0.349484
rb_mean               0.090325
grant_mean            0.031355
sinr_mean             0.023991
sinr_min              0.021451
mr_throughput_mean    0.016851
mcs_mean              0.016639
avg_tilt              0.011938
rsrp_gap              0.007128
dtype: float64

/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

In [283]:
from sklearn.tree import export_text

tree = model.estimators_[0].estimators_[0]  # first tree of first label

print(export_text(tree, feature_names=list(X.columns)))

|--- ho_count <= 0.50
|   |--- throughput_low_ratio <= 0.42
|   |   |--- class: 1.0
|   |--- throughput_low_ratio >  0.42
|   |   |--- class: 0.0
|--- ho_count >  0.50
|   |--- class: 0.0

In [284]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.multioutput import MultiOutputClassifier

model_tree = MultiOutputClassifier(
    DecisionTreeClassifier(max_depth=4)
)

model_tree.fit(X_train, y_train)

y_pred = model_tree.predict(X_test)
print("Tree IoU:", iou_score(y_test, y_pred))

Tree IoU: 0.99625

/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/.venv/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

In [285]:
for i, label in enumerate(LABEL_SPACE):
    acc = (y_test[:, i] == y_pred[:, i]).mean()
    print(f"{label}: {acc:.3f}")

add_neighbor: 1.000
decrease_power: 0.998
increase_power: 1.000
decrease_threshold: 1.000
tilt_down: 0.998
modify_pdcch: 1.000
adjust_azimuth: 1.000
increase_a3: 1.000
tilt_up: 0.998
decrease_a3: 1.000
check_transport: 1.000
insufficient_data: 1.000

In [286]:
from sklearn.tree import export_text

for i, label in enumerate(LABEL_SPACE):
    print(f"\n=== {label} ===")
    tree = model_tree.estimators_[i]
    print(export_text(tree, feature_names=list(X.columns), decimals=3))

=== add_neighbor ===
|--- throughput_low_ratio <= 0.375
|   |--- class: 1.0
|--- throughput_low_ratio >  0.375
|   |--- class: 0.0


=== decrease_power ===
|--- ho_count <= 2.000
|   |--- serving_better_ratio <= 0.542
|   |   |--- class: 1.0
|   |--- serving_better_ratio >  0.542
|   |   |--- ho_count <= 0.500
|   |   |   |--- sinr_min <= -0.145
|   |   |   |   |--- class: 0.0
|   |   |   |--- sinr_min >  -0.145
|   |   |   |   |--- class: 1.0
|   |   |--- ho_count >  0.500
|   |   |   |--- class: 0.0
|--- ho_count >  2.000
|   |--- class: 1.0


=== increase_power ===
|--- mr_rsrp_mean <= -97.995
|   |--- class: 1.0
|--- mr_rsrp_mean >  -97.995
|   |--- class: 0.0


=== decrease_threshold ===
|--- num_cells <= 9.000
|   |--- class: 0.0
|--- num_cells >  9.000
|   |--- class: 1.0


=== tilt_down ===
|--- ho_count <= 2.000
|   |--- serving_better_ratio <= 0.542
|   |   |--- class: 1.0
|   |--- serving_better_ratio >  0.542
|   |   |--- ho_count <= 0.500
|   |   |   |--- sinr_min <= -0.145
|   |   |   |   |--- class: 0.0
|   |   |   |--- sinr_min >  -0.145
|   |   |   |   |--- class: 1.0
|   |   |--- ho_count >  0.500
|   |   |   |--- class: 0.0
|--- ho_count >  2.000
|   |--- class: 1.0


=== modify_pdcch ===
|--- cce_fail_max <= 0.385
|   |--- class: 0.0
|--- cce_fail_max >  0.385
|   |--- class: 1.0


=== adjust_azimuth ===
|--- rsrp_mean <= -94.842
|   |--- class: 1.0
|--- rsrp_mean >  -94.842
|   |--- class: 0.0


=== increase_a3 ===
|--- ho_count <= 2.000
|   |--- class: 0.0
|--- ho_count >  2.000
|   |--- class: 1.0


=== tilt_up ===
|--- rb_mean <= 166.542
|   |--- dl_prb_util <= 57.469
|   |   |--- class: 1.0
|   |--- dl_prb_util >  57.469
|   |   |--- class: 0.0
|--- rb_mean >  166.542
|   |--- class: 0.0


=== decrease_a3 ===
|--- serving_better_ratio <= 0.625
|   |--- sinr_min <= -0.740
|   |   |--- class: 1.0
|   |--- sinr_min >  -0.740
|   |   |--- class: 0.0
|--- serving_better_ratio >  0.625
|   |--- class: 0.0


=== check_transport ===
|--- grant_mean <= 1041.250
|   |--- class: 1.0
|--- grant_mean >  1041.250
|   |--- class: 0.0


=== insufficient_data ===
|--- ul_prb_util <= 56.989
|   |--- class: 0.0
|--- ul_prb_util >  56.989
|   |--- class: 1.0

In [287]:
import numpy as np

def tree_rule_predict(feats):
    pred = {k: 0 for k in LABEL_SPACE}
    
    # ===== add_neighbor =====
    if feats["rrc_reest"] > 0.5:
        pred["add_neighbor"] = 1
    
    # ===== decrease_power =====
    if feats["ho_count"] <= 2:
        if feats["ho_count"] <= 0.5:
            if feats["sinr_min"] > -0.145:
                if feats["rsrp_mean"] > -91.520:
                    pred["decrease_power"] = 1
        # else: class 0
    else:
        pred["decrease_power"] = 1
        pred["tilt_down"] = 1
    
    # ===== increase_power =====
    if feats["rsrp_mean"] <= -94.842:
        pred["increase_power"] = 1
    
    # ===== decrease_threshold =====
    if feats["pci_switches"] > 4.5:
        pred["decrease_threshold"] = 1
    
    # ===== tilt_down =====
    if feats["ho_count"] <= 2:
        if feats["ho_count"] <= 0.5:
            if feats["sinr_min"] > -0.145:
                if feats["rsrp_gap"] <= 3.212:
                    pred["tilt_down"] = 1
        # else: class 0
    else:
        pred["tilt_down"] = 1
    
    # ===== modify_pdcch =====
    if feats["dl_cce_success"] <= 87.746:
        pred["modify_pdcch"] = 1
    
    # ===== adjust_azimuth =====
    if feats["rsrp_mean"] <= -94.842:
        pred["adjust_azimuth"] = 1
    
    # ===== increase_a3 =====
    if feats["ho_count"] > 2:
        pred["increase_a3"] = 1
    
    # ===== tilt_up =====
    if feats["dl_prb_util"] > 22.061:
        if feats["ul_prb_util"] <= 56.989:
            pred["tilt_up"] = 1
    
    # ===== decrease_a3 =====
    if feats["serving_better_ratio"] <= 0.625:
        if feats["sinr_min"] <= -0.740:
            pred["decrease_a3"] = 1
    
    # ===== check_transport =====
    if feats["grant_mean"] <= 1041.250:
        pred["check_transport"] = 1
    
    # ===== insufficient_data =====
    if feats["ul_prb_util"] > 56.989:
        pred["insufficient_data"] = 1
    
    return np.array([pred[k] for k in LABEL_SPACE])

In [288]:
y_tree_rule = np.array([
    tree_rule_predict(f) for _, f in X_train.iterrows()
])

In [289]:
y_tree_rule[0]

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [290]:
y_tree_rule = np.array([
    tree_rule_predict(f) for _, f in X_test.iterrows()
])

print("Tree Rule IoU:", iou_score(y_test, y_tree_rule))

Tree Rule IoU: 1.0

In [291]:
y_tree_rule_all = np.array([
    tree_rule_predict(f) for _, f in X.iterrows()
])

print("Tree Rule IoU:", iou_score(Y, y_tree_rule_all))

Tree Rule IoU: 1.0

In [292]:
for i, label in enumerate(LABEL_SPACE):
    acc = (y_test[:, i] == y_tree_rule[:, i]).mean()
    print(f"{label}: {acc:.3f}")

add_neighbor: 1.000
decrease_power: 1.000
increase_power: 1.000
decrease_threshold: 1.000
tilt_down: 1.000
modify_pdcch: 1.000
adjust_azimuth: 1.000
increase_a3: 1.000
tilt_up: 1.000
decrease_a3: 1.000
check_transport: 1.000
insufficient_data: 1.000

In [293]:
LABEL_SPACE

['add_neighbor',
 'decrease_power',
 'increase_power',
 'decrease_threshold',
 'tilt_down',
 'modify_pdcch',
 'adjust_azimuth',
 'increase_a3',
 'tilt_up',
 'decrease_a3',
 'check_transport',
 'insufficient_data']

In [294]:
def enforce_dependencies(pred):
    idx = {k: i for i, k in enumerate(LABEL_SPACE)}
    
    # power ↔ tilt
    if pred[idx["decrease_power"]] == 1:
        pred[idx["tilt_down"]] = 1
        
    if pred[idx["increase_power"]] == 1:
        pred[idx["adjust_azimuth"]] = 1
    
    return pred

In [295]:
y_tree_rule = np.array([
    enforce_dependencies(tree_rule_predict(f))
    for _, f in X_test.iterrows()
])

print("Tree Rule IoU (fixed):", iou_score(y_test, y_tree_rule))

Tree Rule IoU (fixed): 1.0

In [296]:
###

In [297]:
import re

def extract_option_structure(label):
    label_l = label.lower()
    
    # action type
    if "power" in label_l:
        action = "power"
    elif "tilt" in label_l:
        action = "tilt"
    elif "azimuth" in label_l:
        action = "azimuth"
    elif "a3" in label_l:
        action = "a3_offset"
    elif "pdcch" in label_l:
        action = "pdcch"
    elif "neighbor" in label_l:
        action = "neighbor"
    else:
        action = "other"
    
    # direction
    if "increase" in label_l or "lift" in label_l:
        direction = "increase"
    elif "decrease" in label_l or "press down" in label_l:
        direction = "decrease"
    else:
        direction = "none"
    
    # target cell
    match = re.search(r'(\d+_\d+)', label)
    cell = match.group(1) if match else None
    
    return action, direction, cell

In [298]:
analysis_rows = []

for s in data:
    id_to_label = {opt["id"]: opt["label"] for opt in s["task"]["options"]}
    answers = set(s["answer"].split("|"))
    
    # group options
    groups = {}
    
    for opt in s["task"]["options"]:
        action, direction, cell = extract_option_structure(opt["label"])
        key = (action, direction)
        
        if key not in groups:
            groups[key] = []
        
        groups[key].append({
            "id": opt["id"],
            "cell": cell,
            "is_correct": opt["id"] in answers
        })
    
    # analyze groups
    for (action, direction), opts in groups.items():
        num_same_type = len(opts)
        num_correct = sum(o["is_correct"] for o in opts)
        
        if num_same_type > 1:  # only interesting cases
            analysis_rows.append({
                "scenario_id": s["scenario_id"],
                "action": action,
                "direction": direction,
                "num_options_same_type": num_same_type,
                "num_correct": num_correct
            })

In [299]:
analysis_rows = []

for s in data:
    id_to_label = {opt["id"]: opt["label"] for opt in s["task"]["options"]}
    answers = set(s["answer"].split("|"))
    
    # group options
    groups = {}
    
    for opt in s["task"]["options"]:
        action, direction, cell = extract_option_structure(opt["label"])
        key = (action, direction)
        
        if key not in groups:
            groups[key] = []
        
        groups[key].append({
            "id": opt["id"],
            "cell": cell,
            "is_correct": opt["id"] in answers
        })
    
    # analyze groups
    for (action, direction), opts in groups.items():
        num_same_type = len(opts)
        num_correct = sum(o["is_correct"] for o in opts)
        
        if num_same_type > 1:  # only interesting cases
            analysis_rows.append({
                "scenario_id": s["scenario_id"],
                "action": action,
                "direction": direction,
                "num_options_same_type": num_same_type,
                "num_correct": num_correct
            })

In [300]:
import pandas as pd

df_analysis = pd.DataFrame(analysis_rows)

df_analysis.groupby(["action", "direction"]).agg({
    "num_options_same_type": "mean",
    "num_correct": "mean"
}).sort_values("num_options_same_type", ascending=False)

                     num_options_same_type  num_correct
action    direction
a3_offset decrease                     2.0       0.1155
          increase                     2.0       0.0710
azimuth   none                         2.0       0.0710
neighbor  none                         2.0       0.1200
other     decrease                     2.0       0.1225
          none                         2.0       0.2455
pdcch     none                         2.0       0.1200
power     decrease                     2.0       0.0785
          increase                     2.0       0.0710
tilt      decrease                     2.0       0.0785
          increase                     2.0       0.1270

In [301]:
df_analysis

,scenario_id,action,direction,num_options_same_type,num_correct
0,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,neighbor,none,2,0
1,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,power,decrease,2,1
2,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,power,increase,2,0
3,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,other,none,2,0
4,08e221e5-3ed8-42ed-b7b3-0fd9dfd8d99e,other,decrease,2,0
...,...,...,...,...,...
21995,6a686272-80c5-4a77-ba51-192998460176,tilt,decrease,2,0
21996,6a686272-80c5-4a77-ba51-192998460176,pdcch,none,2,0
21997,6a686272-80c5-4a77-ba51-192998460176,a3_offset,increase,2,0
21998,6a686272-80c5-4a77-ba51-192998460176,other,decrease,2,0
21999,6a686272-80c5-4a77-ba51-192998460176,other,none,2,0

In [302]:
X_test_test = pd.DataFrame([extract_features(s) for s in data_test])

In [303]:
X_test_test

,throughput_mean,throughput_min,throughput_std,throughput_p10,throughput_low_ratio,throughput_drop_ratio,sinr_mean,sinr_min,rsrp_mean,rf_good_flag,...,avg_tilt,pdcch_symbols,dl_prb_util,ul_prb_util,dl_cce_success,dl_cce_util,mr_throughput_mean,mr_rsrp_mean,missing_neighbors,pdcch_problem_score
0,253.883333,55.33,212.195084,58.097,0.500000,0.096609,8.288333,1.39,-82.304167,1,...,4.600000,1.0,13.360740,15.226740,95.550200,0.211640,46.083333,-88.033333,1,0.056266
1,273.370833,21.98,240.093899,53.743,0.500000,0.037747,8.684167,1.19,-82.791667,1,...,5.200000,1.0,12.055020,10.254840,93.075600,0.195460,45.380000,-81.920000,1,0.074107
2,242.737500,28.34,216.244111,37.529,0.500000,0.047468,9.070000,1.48,-82.536667,1,...,5.600000,1.0,9.900780,12.066560,93.636400,0.215080,54.450000,-80.462500,1,0.071591
3,258.905833,33.13,227.808014,41.874,0.500000,0.057911,9.216667,2.00,-83.150000,1,...,2.400000,1.0,10.259520,9.977740,93.796800,0.123440,40.500000,-89.383333,1,0.057360
4,250.440000,25.41,223.128082,37.324,0.500000,0.042041,8.786667,1.77,-84.368333,1,...,3.800000,1.0,12.226260,8.640200,92.872000,0.199080,43.080000,-87.140000,1,0.073884
5,218.804167,34.99,170.784728,54.086,0.500000,0.081091,7.921667,1.09,-85.029167,0,...,1.500000,1.0,11.153850,10.836450,94.393500,0.158400,70.383333,-94.600000,1,0.079320
6,257.834167,23.37,208.240315,60.787,0.500000,0.043701,7.795000,-1.33,-96.527500,0,...,9.750000,1.0,14.537825,11.371875,93.042500,0.182875,50.533333,-102.833333,1,0.062123
7,240.526667,20.70,209.132995,31.173,0.500000,0.036940,8.176667,-1.54,-97.768333,0,...,4.500000,1.0,12.896925,11.834050,92.924750,0.235875,51.771429,-107.814286,1,0.059142
8,240.335000,20.14,218.676217,31.253,0.500000,0.034956,7.180833,-1.42,-97.175833,0,...,3.750000,1.0,11.266075,11.834250,94.731500,0.145100,56.928571,-108.800000,1,0.059555
9,279.290000,53.97,222.833709,67.704,0.500000,0.092267,8.501667,0.43,-83.690000,1,...,4.000000,1.0,14.601975,13.442325,93.730250,0.166850,53.933333,-88.800000,1,0.076309
10,267.157500,45.56,218.835010,51.004,0.500000,0.086355,9.002500,1.75,-82.026667,1,...,4.400000,1.0,16.312560,14.300860,94.599000,0.187000,45.050000,-81.237500,1,0.070786
11,259.289167,25.61,227.174089,38.297,0.500000,0.043323,8.627500,1.15,-82.119167,1,...,4.200000,1.0,9.822100,11.662320,94.489000,0.211160,40.540000,-87.960000,1,0.082783
12,250.120000,25.17,203.470198,28.313,0.416667,0.045770,8.313333,-2.82,-83.081667,1,...,10.000000,1.0,13.167700,14.231050,94.728750,0.127550,119.485714,-81.757143,1,0.069147
13,277.530833,30.57,216.481076,48.783,0.416667,0.052776,7.829167,-3.51,-83.715833,0,...,10.250000,1.0,13.423725,12.998000,94.454250,0.200425,67.185714,-84.228571,1,0.054971
14,236.592500,27.85,171.105105,47.238,0.416667,0.059772,7.503333,-3.16,-83.171667,0,...,6.500000,1.0,11.832100,16.388800,92.283500,0.187350,108.660000,-88.600000,1,0.066066
15,267.328333,57.12,205.187292,63.008,0.500000,0.101478,13.080000,7.09,-90.381667,1,...,9.000000,1.0,28.439175,29.728450,93.982250,0.190500,61.414286,-85.414286,1,0.065553
16,280.520833,68.04,227.194445,68.991,0.500000,0.113277,12.736667,7.07,-89.930833,1,...,7.000000,1.0,27.457750,32.096375,94.137000,0.153525,61.533333,-89.633333,1,0.050506
17,269.607500,57.70,204.950273,73.779,0.500000,0.101706,11.970000,7.22,-90.802500,1,...,5.000000,1.0,28.647275,28.853350,94.558250,0.234600,55.800000,-88.914286,1,0.064659
18,184.797500,63.12,194.987810,67.004,0.750000,0.115082,7.390000,3.35,-93.125833,0,...,6.846154,1.0,11.843300,11.415523,93.249154,0.172269,116.616667,-93.883333,1,0.056919
19,179.610833,54.61,198.379845,62.687,0.750000,0.095795,6.579167,2.09,-91.794167,0,...,7.076923,1.0,11.958592,11.797823,93.942077,0.183600,89.128571,-92.514286,1,0.074007
20,167.742500,49.37,160.985376,72.537,0.750000,0.087885,6.560000,2.42,-92.591667,0,...,6.461538,1.0,13.695300,13.292300,93.559846,0.179138,97.900000,-93.740000,1,0.078487
21,240.717500,53.08,183.333847,58.709,0.500000,0.110759,13.145833,7.12,-90.208333,1,...,6.250000,1.0,10.685250,11.870750,80.835250,0.347325,46.833333,-90.050000,1,0.233328
22,294.050000,59.01,241.663889,66.388,0.500000,0.097981,13.112500,9.07,-91.222500,1,...,6.500000,1.0,11.183150,14.982650,81.081500,0.356425,56.350000,-89.512500,1,0.251339
23,326.551667,35.96,214.648046,46.711,0.333333,0.064629,9.894167,-1.50,-83.738333,1,...,2.250000,1.0,13.538850,10.856275,92.987500,0.088800,74.828571,-93.642857,1,0.070621
24,310.920833,32.22,209.947466,35.739,0.333333,0.056783,9.332500,-3.02,-82.724167,1,...,3.500000,1.0,12.554450,9.349150,93.343500,0.167475,128.262500,-89.800000,1,0.067470
25,322.903333,42.17,207.656917,44.224,0.333333,0.081758,9.975000,-3.55,-82.282500,1,...,3.000000,1.0,17.741900,12.671875,93.684750,0.173225,71.442857,-86.528571,1,0.069362
26,314.658333,25.01,208.826027,55.136,0.333333,0.042302,8.960000,-3.89,-83.417500,1,...,5.500000,1.0,10.413250,14.053875,93.446250,0.110200,125.750000,-85.450000,1,0.074661
27,267.605000,24.11,168.826811,46.824,0.333333,0.052764,9.308333,-3.88,-84.435833,1,...,4.250000,1.0,8.720925,12.278450,94.535250,0.144350,86.520000,-87.080000,1,0.068061

In [304]:
throughput_mean: 310.1041666666667
throughput_min: 29.24
throughput_std: 205.501041291692
sinr_mean: 8.983333333333333
sinr_min: -3.89
rsrp_mean: -82.89
pci_switches: 1
rsrp_gap: -0.30666666666666603
ho_count: 0
a3_count: 0 #wrong
rrc_reest: 0 #wrong
num_cells: 4
avg_power: 26.0
avg_tilt: 4.0
dl_prb_util: 12.793975
ul_prb_util: 16.0804
mr_throughput_mean: 143.40000000000003
mr_rsrp_mean: -88.58571428571429
missing_neighbors: 1

In [307]:
data_path_test = '../data/Phase_1/raw/test.json'
with open(data_path_test) as f:
    data_test = json.load(f)

len(data_test)

500

In [308]:
X_hold = pd.DataFrame([extract_features(s) for s in data_test])
X_hold = X_hold.fillna(0)

In [309]:
X_hold

,throughput_mean,throughput_min,throughput_std,throughput_p10,throughput_low_ratio,throughput_drop_ratio,sinr_mean,sinr_min,rsrp_mean,rf_good_flag,...,avg_tilt,pdcch_symbols,dl_prb_util,ul_prb_util,dl_cce_success,dl_cce_util,mr_throughput_mean,mr_rsrp_mean,missing_neighbors,pdcch_problem_score
0,310.104167,29.24,205.501041,33.641,0.333333,0.055984,8.983333,-3.89,-82.890000,1,...,4.000000,1.0,12.793975,16.080400,93.663750,0.171625,143.400000,-88.585714,1,0.072342
1,149.419167,41.70,168.030954,52.611,0.750000,0.073758,6.535000,2.29,-91.900833,0,...,6.230769,1.0,11.897577,13.789885,93.443231,0.188400,91.450000,-94.737500,1,0.076754
2,248.883333,52.94,201.495951,54.688,0.500000,0.095456,11.810833,8.18,-90.007500,1,...,4.000000,1.0,80.306850,88.597000,92.653000,0.157800,52.500000,-86.100000,1,0.076208
3,180.494167,54.23,195.717925,57.692,0.750000,0.100411,5.669167,2.26,-92.257500,0,...,6.615385,1.0,9.971485,14.056377,94.687615,0.172362,129.712500,-94.925000,1,0.054687
4,319.400000,32.04,211.964279,52.808,0.333333,0.053988,9.780000,-2.91,-84.399167,1,...,6.500000,1.0,10.291425,11.016675,93.140500,0.177425,102.000000,-92.060000,1,0.058912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,260.172500,61.09,200.214194,68.151,0.500000,0.101868,13.191667,7.83,-90.578333,1,...,6.500000,1.0,29.019525,33.208075,92.249500,0.137450,61.583333,-91.000000,1,0.066585
496,252.582500,55.87,189.503858,70.589,0.500000,0.111399,12.523333,7.77,-90.152500,1,...,9.500000,1.0,31.643425,26.671325,94.919500,0.186625,47.385714,-87.985714,1,0.058992
497,275.305000,22.65,184.054972,42.002,0.333333,0.042201,9.730833,-3.52,-83.447500,1,...,8.500000,1.0,10.436000,14.421575,92.907500,0.226650,118.942857,-91.857143,1,0.066277
498,301.652500,45.41,196.715871,47.811,0.333333,0.080865,9.689167,-3.76,-82.867500,1,...,4.750000,1.0,9.789875,11.378950,91.136500,0.201675,111.100000,-84.300000,1,0.083674
499,265.170833,35.88,225.775684,39.398,0.500000,0.062743,8.465000,1.40,-82.978333,1,...,5.000000,1.0,13.218100,11.264660,94.439400,0.202320,54.528571,-87.228571,1,0.050848

In [310]:
y_tree_rule_hold = np.array([
    tree_rule_predict(f) for _, f in X_hold.iterrows()
])

In [311]:
y_tree_rule_hold

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], shape=(500, 12))

In [312]:
LABEL_SPACE

['add_neighbor',
 'decrease_power',
 'increase_power',
 'decrease_threshold',
 'tilt_down',
 'modify_pdcch',
 'adjust_azimuth',
 'increase_a3',
 'tilt_up',
 'decrease_a3',
 'check_transport',
 'insufficient_data']

In [313]:
df_hold = pd.DataFrame(y_tree_rule_hold, columns=LABEL_SPACE)

In [314]:
df_hold

,add_neighbor,decrease_power,increase_power,decrease_threshold,tilt_down,modify_pdcch,adjust_azimuth,increase_a3,tilt_up,decrease_a3,check_transport,insufficient_data
0,1,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,1
3,0,0,0,1,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,0,0,0,0,0,0,0,1,0,0,0
496,0,0,0,0,0,0,0,0,1,0,0,0
497,1,0,0,0,0,0,0,0,0,0,0,0
498,1,0,0,0,0,0,0,0,0,0,0,0
499,0,1,0,0,1,0,0,1,0,0,0,0

In [315]:
counts = y_tree_rule_hold.sum(axis=0)
summary = dict(zip(LABEL_SPACE, counts))

In [316]:
summary

{'add_neighbor': np.int64(64),
 'decrease_power': np.int64(40),
 'increase_power': np.int64(27),
 'decrease_threshold': np.int64(59),
 'tilt_down': np.int64(40),
 'modify_pdcch': np.int64(64),
 'adjust_azimuth': np.int64(27),
 'increase_a3': np.int64(20),
 'tilt_up': np.int64(50),
 'decrease_a3': np.int64(73),
 'check_transport': np.int64(65),
 'insufficient_data': np.int64(58)}

In [317]:
from scipy.sparse import coo_matrix

In [318]:
co_matrix = y_tree_rule_hold.T @ y_tree_rule_hold

In [319]:
coo_labels = coo_matrix(co_matrix)

In [320]:
label_edges = [
    (LABEL_SPACE[r], LABEL_SPACE[c], v)
    for r, c, v in zip(coo_labels.row, coo_labels.col, coo_labels.data)
    if r != c
]

In [321]:
label_edges

[('decrease_power', 'tilt_down', np.int64(40)),
 ('decrease_power', 'increase_a3', np.int64(20)),
 ('increase_power', 'adjust_azimuth', np.int64(27)),
 ('tilt_down', 'decrease_power', np.int64(40)),
 ('tilt_down', 'increase_a3', np.int64(20)),
 ('adjust_azimuth', 'increase_power', np.int64(27)),
 ('increase_a3', 'decrease_power', np.int64(20)),
 ('increase_a3', 'tilt_down', np.int64(20))]

In [322]:
pd.DataFrame(co_matrix, index=LABEL_SPACE, columns=LABEL_SPACE)

,add_neighbor,decrease_power,increase_power,decrease_threshold,tilt_down,modify_pdcch,adjust_azimuth,increase_a3,tilt_up,decrease_a3,check_transport,insufficient_data
add_neighbor,64,0,0,0,0,0,0,0,0,0,0,0
decrease_power,0,40,0,0,40,0,0,20,0,0,0,0
increase_power,0,0,27,0,0,0,27,0,0,0,0,0
decrease_threshold,0,0,0,59,0,0,0,0,0,0,0,0
tilt_down,0,40,0,0,40,0,0,20,0,0,0,0
modify_pdcch,0,0,0,0,0,64,0,0,0,0,0,0
adjust_azimuth,0,0,27,0,0,0,27,0,0,0,0,0
increase_a3,0,20,0,0,20,0,0,20,0,0,0,0
tilt_up,0,0,0,0,0,0,0,0,50,0,0,0
decrease_a3,0,0,0,0,0,0,0,0,0,73,0,0
check_transport,0,0,0,0,0,0,0,0,0,0,65,0
insufficient_data,0,0,0,0,0,0,0,0,0,0,0,58

In [323]:
# Cell 94 - Paths for 500->550 submission export
import os
import json
import numpy as np
import pandas as pd

RAW_TEST_500_PATH = "/Users/faiqrindha/Documents/ZindiAfrica/Telco-Troubleshooting-Agentic-Challenge/Track A/data/Phase_1/raw/test.json"
SAMPLE_SUBMISSION_PATH = "/Users/faiqrindha/Documents/ZindiAfrica/Telco-Troubleshooting-Agentic-Challenge/Track A/sample_submission.csv"
OUT_SUBMISSION_PATH = "/Users/faiqrindha/Documents/ZindiAfrica/Bismillah/Track A/results/result_TrackA_tuned_550.csv"

with open(RAW_TEST_500_PATH) as f:
    raw_test_500 = json.load(f)

sample_submission = pd.read_csv(SAMPLE_SUBMISSION_PATH)

print("raw_test_500:", len(raw_test_500))
print("sample_submission:", len(sample_submission))
print("df_hold rows:", len(df_hold))

raw_test_500: 500
sample_submission: 550
df_hold rows: 500

In [324]:
# Cell 95 - Decode df_hold (12 labels) into per-scenario C-IDs
from collections import Counter


def category_multiplicity_from_train(train_rows):
    by_cat = {cat: [] for cat in LABEL_SPACE}

    for s in train_rows:
        id_to_label = {o["id"]: o["label"] for o in s["task"]["options"]}
        local = Counter()

        for cid in str(s.get("answer", "")).split("|"):
            if not cid:
                continue
            lbl = id_to_label.get(cid)
            if lbl is None:
                continue
            cat = map_to_category(normalize_label(lbl))
            if cat in LABEL_SPACE:
                local[cat] += 1

        for cat, v in local.items():
            by_cat[cat].append(v)

    out = {}
    for cat, vals in by_cat.items():
        out[cat] = max(1, int(round(float(np.median(vals))))) if vals else 1
    return out


def c_key(cid):
    return int(str(cid).replace("C", ""))


def build_cat_to_ids(scenario):
    out = {cat: [] for cat in LABEL_SPACE}
    for opt in scenario["task"]["options"]:
        cat = map_to_category(normalize_label(opt["label"]))
        if cat in out:
            out[cat].append(opt["id"])
    for cat in out:
        out[cat] = sorted(out[cat], key=c_key)
    return out


def decode_row(row_vals, scenario, cat_mult):
    cat_to_ids = build_cat_to_ids(scenario)

    active = []
    for i, cat in enumerate(LABEL_SPACE):
        if int(row_vals[i]) == 1 and len(cat_to_ids[cat]) > 0:
            active.append(cat)

    if len(active) == 0:
        # fallback: pick first available category in this scenario
        for cat in LABEL_SPACE:
            if len(cat_to_ids[cat]) > 0:
                active = [cat]
                break

    selected = []
    for cat in active:
        ids = cat_to_ids[cat]
        k = min(len(ids), int(cat_mult.get(cat, 1)))
        selected.extend(ids[:k])

    selected = sorted(set(selected), key=c_key)

    tag = scenario.get("tag", "single-answer")
    if tag == "single-answer":
        if len(selected) == 0:
            selected = [scenario["task"]["options"][0]["id"]]
        selected = selected[:1]
    else:
        if len(selected) < 2:
            all_ids = sorted([o["id"] for o in scenario["task"]["options"]], key=c_key)
            for cid in all_ids:
                if cid not in selected:
                    selected.append(cid)
                if len(selected) >= 2:
                    break
        if len(selected) > 4:
            selected = selected[:4]

    selected = sorted(set(selected), key=c_key)
    return "|".join(selected)


if len(df_hold) != len(raw_test_500):
    raise ValueError(f"Row mismatch: df_hold={len(df_hold)} vs raw_test_500={len(raw_test_500)}")

cat_mult = category_multiplicity_from_train(data)

pred_500 = pd.DataFrame({
    "ID": [s["scenario_id"] for s in raw_test_500],
    "Track A": [decode_row(df_hold.iloc[i].values, raw_test_500[i], cat_mult) for i in range(len(raw_test_500))]
})

print("pred_500 rows:", len(pred_500))
print(pred_500.head())

pred_500 rows: 500
                                     ID Track A
0  80e3aa96-815d-4683-980c-16db42eab0ef      C1
1  f55a819f-3fb9-4c8f-8859-a5b1649ff2d5      C4
2  2cd1f674-a411-4860-82c6-a16ba624b172      C8
3  923c459f-2ead-4c18-a204-751574ed6ae3      C1
4  2e83ae4f-dca0-4931-bb13-d13d672e14e1     C21

In [325]:
# Cell 96 - Merge 500 Track A predictions into 550 template and save
sub = sample_submission.copy()
if "scenario_id" in sub.columns and "ID" not in sub.columns:
    sub = sub.rename(columns={"scenario_id": "ID"})

if "Track A" not in sub.columns:
    sub["Track A"] = ""
if "Track B" not in sub.columns:
    sub["Track B"] = ""

pred_map = dict(zip(pred_500["ID"], pred_500["Track A"]))
sub["Track A"] = sub["ID"].map(pred_map).fillna(sub["Track A"]).fillna("")
sub["Track B"] = ""

sub = sub[["ID", "Track A", "Track B"]]
os.makedirs(os.path.dirname(OUT_SUBMISSION_PATH), exist_ok=True)
sub.to_csv(OUT_SUBMISSION_PATH, index=False)

print("saved:", OUT_SUBMISSION_PATH)
print("rows:", len(sub))
print("Track A filled:", (sub["Track A"].astype(str).str.strip() != "").sum())
print("Track B filled:", (sub["Track B"].astype(str).str.strip() != "").sum())
sub.head()

saved: /Users/faiqrindha/Documents/ZindiAfrica/Bismillah/Track A/results/result_TrackA_tuned_550.csv
rows: 550
Track A filled: 500
Track B filled: 0

                                     ID Track A Track B
0  80e3aa96-815d-4683-980c-16db42eab0ef      C1
1  f55a819f-3fb9-4c8f-8859-a5b1649ff2d5      C4
2  2cd1f674-a411-4860-82c6-a16ba624b172      C8
3  923c459f-2ead-4c18-a204-751574ed6ae3      C1
4  2e83ae4f-dca0-4931-bb13-d13d672e14e1     C21